services:
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    container_name: qwen-server

    ports:
      - "8080:8080"

    volumes:
      - llama-models:/root/.cache

    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

    command:
      - -hf
      - Qwen/Qwen3-VL-2B-Instruct-GGUF:Q4_K_M
      - --jinja
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --n-gpu-layers
      - "99"

volumes:
  llama-models: